print("Giorgi Tamarashvili")
print("Zurab Kavtaradze")
print("Saba Gotsiridze")
print("Irakli Guliashvili")
print("Natia tabatadze")
print("Davit Tchkadua")
print("Avto Darbaidze")
print("Salome Samkurashvili")
print("Saba Gotsiridze from git")
print("Teimuraz Kviloria")
print("giorgi injgia")
print("zura zumbadze")
print("Guram Asanidze")
print("avto darbaidze")
print("mariam tsamalashvili")
